#!/bin/bash

fileName=$1
fileName=${fileName:?"missing"}

# We cannot reassign position parameters. Hence, we use create another variable
# to bypass the limit.
howMany=$2

sort -nr $fileName | head -${howMany:=7}
