#!/bin/bash

for tryfile in "$@"; do
  echo $tryfile
  if [ -d "$tryfile" ]; then # -d works properly when we open a new subshell.
    builtin cd $tryfile
    ~/BashLearning/tracefile $(ls) # this will start a subshell.
    # all local variables will NOT be carried over to the new subshell.
    builtin cd ..
  fi
done
